/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.excilys.sugadroid;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int background=0x7f050000;
        public static final int detail_text=0x7f050002;
        public static final int important_text=0x7f050001;
    }
    public static final class drawable {
        public static final int about=0x7f020000;
        public static final int companies=0x7f020001;
        public static final int company=0x7f020002;
        public static final int contact=0x7f020003;
        public static final int contacts=0x7f020004;
        public static final int date=0x7f020005;
        public static final int email=0x7f020006;
        public static final int icon=0x7f020007;
        public static final int map=0x7f020008;
        public static final int phone=0x7f020009;
        public static final int telephone=0x7f02000a;
    }
    public static final class id {
        public static final int about=0x7f080023;
        public static final int account_list_button=0x7f08001d;
        public static final int account_name_text=0x7f080000;
        public static final int address_button=0x7f080002;
        public static final int address_text=0x7f080001;
        public static final int appointment_date_start=0x7f080005;
        public static final int appointment_description_text=0x7f080008;
        public static final int appointment_duration=0x7f080006;
        public static final int appointment_info_text=0x7f080009;
        public static final int appointment_name_text=0x7f080007;
        public static final int appointment_subject=0x7f080010;
        public static final int appointment_time=0x7f080011;
        public static final int appointments_button=0x7f08001e;
        public static final int appointments_day=0x7f08000b;
        public static final int appointments_flipper=0x7f08000e;
        public static final int appointments_list=0x7f08000f;
        public static final int back_to_menu_settings=0x7f080020;
        public static final int connection_settings=0x7f080021;
        public static final int contact_account_button=0x7f080014;
        public static final int contact_add_button=0x7f080018;
        public static final int contact_email_button=0x7f080017;
        public static final int contact_info_text=0x7f080013;
        public static final int contact_list_button=0x7f08001c;
        public static final int contact_name_text=0x7f080012;
        public static final int contact_phone_mobile_button=0x7f080015;
        public static final int contact_phone_work_button=0x7f080016;
        public static final int info_message=0x7f080004;
        public static final int item_search_edit=0x7f080019;
        public static final int item_search_info_message=0x7f08001a;
        public static final int item_search_list=0x7f08001b;
        public static final int loading=0x7f08000d;
        public static final int login_info=0x7f08001f;
        public static final int next_day_button=0x7f08000c;
        public static final int phone_button=0x7f080003;
        public static final int previous_day_button=0x7f08000a;
        public static final int settings=0x7f080022;
    }
    public static final class layout {
        public static final int account_details=0x7f030000;
        public static final int appointment_details=0x7f030001;
        public static final int appointments=0x7f030002;
        public static final int appointments_page=0x7f030003;
        public static final int appointments_row=0x7f030004;
        public static final int contact_details=0x7f030005;
        public static final int item_list=0x7f030006;
        public static final int menu=0x7f030007;
        public static final int top=0x7f030008;
    }
    public static final class menu {
        public static final int back_to_menu=0x7f070000;
        public static final int menu=0x7f070001;
    }
    public static final class string {
        public static final int about_button=0x7f060044;
        public static final int about_text=0x7f060026;
        /**  ********* About texts ********* 
         */
        public static final int about_title=0x7f060025;
        public static final int account_list_button=0x7f060042;
        public static final int account_max_results_pref_summary=0x7f060030;
        public static final int account_max_results_pref_text=0x7f06002f;
        public static final int activity_account_details=0x7f060004;
        public static final int activity_account_list=0x7f060002;
        public static final int activity_appointment_details=0x7f060005;
        public static final int activity_appointments=0x7f060006;
        public static final int activity_connection_settings=0x7f060007;
        public static final int activity_contact_details=0x7f060003;
        /**  ********* Activity titles ********* 
         */
        public static final int activity_contact_list=0x7f060001;
        public static final int activity_general_settings=0x7f060008;
        public static final int add_contact=0x7f06005b;
        public static final int address_button=0x7f06004d;
        /**  ********* Application name ********* 
         */
        public static final int app_name=0x7f060000;
        public static final int appointment_date_end=0x7f060057;
        public static final int appointment_date_start=0x7f060055;
        public static final int appointment_duration=0x7f060058;
        public static final int appointment_hours=0x7f060059;
        public static final int appointment_name=0x7f060054;
        public static final int appointment_time_start=0x7f060056;
        public static final int appointments_button=0x7f060043;
        public static final int appointments_loading_after_pref_summary=0x7f060036;
        public static final int appointments_loading_after_pref_text=0x7f060035;
        public static final int appointments_loading_before_pref_summary=0x7f060034;
        public static final int appointments_loading_before_pref_text=0x7f060033;
        public static final int back_to_menu_label=0x7f060023;
        public static final int back_to_menu_shortcut=0x7f060024;
        public static final int connection_settings_label=0x7f060021;
        public static final int connection_settings_shortcut=0x7f060022;
        public static final int contact_added_message=0x7f060012;
        public static final int contact_added_title=0x7f060011;
        public static final int contact_list=0x7f060053;
        public static final int contact_list_button=0x7f060041;
        public static final int day_date_format=0x7f060050;
        public static final int day_not_loaded_message=0x7f060010;
        public static final int day_not_loaded_title=0x7f06000f;
        public static final int default_account_max_results=0x7f06003b;
        public static final int default_appointments_loading_after=0x7f06003e;
        public static final int default_appointments_loading_before=0x7f06003d;
        public static final int default_gmt=0x7f06003c;
        public static final int default_password=0x7f060038;
        public static final int default_search_list_max_results=0x7f06003a;
        public static final int default_url=0x7f060039;
        /**  default values for preferences 
 The following 8 next entries does not need to be translated 
         */
        public static final int default_username=0x7f060037;
        public static final int dialog_OK_button=0x7f060013;
        public static final int dialog_unknow_error_message=0x7f060015;
        public static final int dialog_unknow_error_title=0x7f060014;
        public static final int error_launch_task_message=0x7f06000a;
        /**  ********* Dialog box messages ********* 
         */
        public static final int error_launch_task_title=0x7f060009;
        public static final int error_login_failed_message=0x7f06000c;
        public static final int error_login_failed_title=0x7f06000b;
        public static final int gmt_pref_summary=0x7f060032;
        public static final int gmt_pref_text=0x7f060031;
        public static final int invalid_response_message=0x7f06000e;
        public static final int invalid_response_title=0x7f06000d;
        public static final int item_search_hint=0x7f060045;
        public static final int item_search_more_result=0x7f060047;
        public static final int item_search_no_result=0x7f060046;
        public static final int loading_text=0x7f060040;
        public static final int logged_in_message=0x7f060048;
        public static final int logged_out_message=0x7f060049;
        public static final int loging_in_message=0x7f06004a;
        public static final int next_day_button=0x7f06004f;
        public static final int not_available=0x7f06005a;
        public static final int not_logged_in_message=0x7f06004c;
        public static final int not_logged_in_title=0x7f06004b;
        public static final int password_pref_summary=0x7f06002a;
        public static final int password_pref_text=0x7f060029;
        public static final int previous_day_button=0x7f06004e;
        public static final int search_max_results_pref_summary=0x7f06002e;
        public static final int search_max_results_pref_text=0x7f06002d;
        /**  ********* Menu texts ********* 
         */
        public static final int settings_label=0x7f06001f;
        public static final int settings_shortcut=0x7f060020;
        public static final int time_format=0x7f060051;
        public static final int toast_login_failed=0x7f060018;
        public static final int toast_login_failed_bad_credentials=0x7f060017;
        /**  ********* Toast texts ********* 
 Toast Login 
 ********* Toast texts ********* 
 Toast Login 
         */
        public static final int toast_login_failed_no_network=0x7f060016;
        public static final int toast_login_in=0x7f06001a;
        public static final int toast_login_successful=0x7f060019;
        public static final int toast_service_call_failed=0x7f06001c;
        /**  Toast Service 
 Toast Service 
         */
        public static final int toast_service_call_failed_no_network=0x7f06001b;
        public static final int toast_service_no_session=0x7f06001d;
        public static final int toast_service_session_invalid=0x7f06001e;
        public static final int today=0x7f060052;
        /**  Top view 
         */
        public static final int top_logged_in=0x7f06005c;
        public static final int top_login_in=0x7f06005e;
        public static final int top_not_logged_in=0x7f06005d;
        public static final int url_pref_summary=0x7f06002c;
        public static final int url_pref_text=0x7f06002b;
        public static final int username_pref_summary=0x7f060028;
        /**  ********* Settings texts ********* 
         */
        public static final int username_pref_text=0x7f060027;
        /**  ********* View texts ********* 
         */
        public static final int welcome_text=0x7f06003f;
    }
    public static final class xml {
        public static final int connection_settings=0x7f040000;
        public static final int settings=0x7f040001;
    }
}
